//! Wifi profile extraction via netsh (Get-WifiProfileNames / Get-WifiLines).
//! netsh is absent on Win9x/NT4 -> graceful skip, matching install.ps1.

use crate::sys::{capture, out};

/// Saved wifi profile names (parsed from `netsh wlan show profiles`).
pub fn wifi_profile_names() -> Vec<String> {
    let raw = match capture("netsh.exe", &["wlan".into(), "show".into(), "profiles".into()]) {
        Some((code, out_text)) if code == 0 => out_text,
        _ => return Vec::new(),
    };
    let mut names = Vec::new();
    for line in raw.lines() {
        // Each profile line looks like: '    All User Profile     : <name>'.
        // Split on the first colon only so names containing ':' stay intact.
        if line.contains("All User Profile") {
            if let Some(idx) = line.find(':') {
                let n = line[idx + 1..].trim();
                if !n.is_empty() {
                    names.push(n.to_string());
                }
            }
        }
    }
    names.sort();
    names.dedup();
    names
}

fn psk_for_profile(name: &str) -> Option<String> {
    let (_, detail) = capture(
        "netsh.exe",
        &[
            "wlan".into(),
            "show".into(),
            "profile".into(),
            format!("name={}", name),
            "key=clear".into(),
        ],
    )?;
    for line in detail.lines() {
        // '    Key Content            : <psk>'
        if line.contains("Key Content") {
            if let Some(idx) = line.find(':') {
                let psk = line[idx + 1..].trim();
                if !psk.is_empty() {
                    return Some(psk.to_string());
                }
            }
        }
    }
    None
}

fn shell_quote(s: &str) -> String {
    s.replace('\'', "'\\''")
}

/// wifi.sh connect lines for the chosen profiles (Get-WifiLines).
pub fn wifi_lines(profiles: &[String]) -> Vec<String> {
    let mut lines = Vec::new();
    if !has_netsh() {
        return lines;
    }
    let profiles: Vec<String> = if profiles.is_empty() {
        wifi_profile_names()
    } else {
        profiles.to_vec()
    };
    for n in &profiles {
        if let Some(psk) = psk_for_profile(n) {
            lines.push(format!(
                "nmcli device wifi connect '{}' password '{}'",
                shell_quote(n),
                shell_quote(&psk)
            ));
        }
        // Open networks / password not saved are skipped, as in install.ps1.
    }
    lines
}

pub fn has_netsh() -> bool {
    // capture() returns None when the tool is missing (9x/NT4)
    if crate::sys::os_ver() == crate::sys::OsVer::Win9x {
        return false;
    }
    capture("netsh.exe", &[ "?".into() ]).is_some()
}

/// Full wifi.sh content (header + connect lines), or None when empty.
pub fn generate_wifi_sh(profiles: &[String]) -> Option<(String, usize)> {
    let lines = wifi_lines(profiles);
    if lines.is_empty() {
        out::warn("No saved wifi profile with a retrievable key found; wifi.sh not written.");
        return None;
    }
    let n = lines.len();
    let mut body = String::from(
        "#!/bin/bash\n# Generated by lsl-usb installer from Windows saved profiles (netsh).\n",
    );
    for l in lines {
        body.push_str(&l);
        body.push('\n');
    }
    Some((body, n))
}
