// Compiles the lsl-hw-cache snapshot (../../lsl-hw-cache/*.html) into a
// compact per-device summary embedded in the binary, so common hardware is
// rated instantly with no network request (the live linux-hardware.org path
// has a 10s crawl-delay per device).

use std::env;
use std::fs;
use std::path::Path;

fn find_between<'a>(s: &'a str, start: &str, end: &str) -> Option<&'a str> {
    let i = s.find(start)? + start.len();
    let rest = &s[i..];
    let j = rest.find(end)?;
    Some(&rest[..j])
}

/// Same heuristics as the runtime parser in src/hardware.rs.
fn parse_page(html: &str) -> (String, String, String, Vec<String>) {
    let mut name = String::new();
    let mut ksup = String::new();
    let mut src = String::new();
    let mut third = Vec::new();

    if let Some(n) = find_between(html, "<h2 class='top'>Device '", "'") {
        name = n.to_string();
    }
    if let Some(k) = find_between(html, "supported by kernel versions <a", "</a>") {
        let k = match k.find('>') {
            Some(i) => &k[i + 1..],
            None => k,
        };
        ksup = k.to_string();
    }
    if let Some(seg) = find_between(html, "&nbsp;-&nbsp;</td>", "</td><td>") {
        src = seg.to_string();
    } else if let Some(seg) = find_between(html, "<td>", "</td>") {
        if seg.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
            src = seg.to_string();
        }
    }
    let mut from = 0;
    while let Some(rel) = html[from..].find("<a href=\"https://github.com/") {
        let start = from + rel + "<a href=\"https://github.com/".len();
        let rest = &html[start..];
        if let Some(q) = rest.find('"') {
            third.push(rest[..q].to_string());
            from = start + q;
        } else {
            break;
        }
    }
    (name, ksup, src, third)
}

fn esc(s: &str) -> String {
    // escape for a Rust string literal
    let mut out = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => {}
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let cache_dir = Path::new(&manifest).join("..").join("..").join("lsl-hw-cache");
    let mut entries: Vec<(String, String, String, String, Vec<String>)> = Vec::new();
    if let Ok(rd) = fs::read_dir(&cache_dir) {
        let mut files: Vec<_> = rd
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.extension().map(|e| e == "html").unwrap_or(false))
            .collect();
        files.sort();
        for p in files {
            // lsl-lhw-<kind>-<vid>-<did>.html  ->  <kind>:<vid>-<did>
            let stem = p.file_stem().unwrap().to_string_lossy().into_owned();
            let id = stem
                .strip_prefix("lsl-lhw-")
                .unwrap_or(&stem)
                .replacen('-', ":", 1);
            if !id.contains(':') {
                continue;
            }
            let Ok(html) = fs::read_to_string(&p) else { continue };
            let (name, ksup, src, third) = parse_page(&html);
            entries.push((id, name, ksup, src, third));
        }
    }

    let out_dir = env::var("OUT_DIR").unwrap();
    let dst = Path::new(&out_dir).join("hw_cache_embedded.rs");
    let mut code = String::new();
    code.push_str("// AUTO-GENERATED by build.rs from the lsl-hw-cache snapshot.\n");
    code.push_str("// (id, device name, kernel support, driver source, out-of-tree repos)\n");
    code.push_str(&format!(
        "pub static EMBEDDED_HW_CACHE: [(&str, &str, &str, &str, &[&str]); {}] = [\n",
        entries.len()
    ));
    for (id, name, ksup, src, third) in &entries {
        let tps: Vec<String> = third.iter().map(|t| format!("\"{}\"", esc(t))).collect();
        code.push_str(&format!(
            "    (\"{}\", \"{}\", \"{}\", \"{}\", &[{}]),\n",
            esc(id),
            esc(name),
            esc(ksup),
            esc(src),
            tps.join(", ")
        ));
    }
    code.push_str("];\n");
    fs::write(&dst, code).unwrap();
    println!(
        "cargo:warning=embedded LKDDb cache summary: {} devices",
        entries.len()
    );
}
